Feature/pocketlisp/divisors
zsebtanar/zsebtanar-proto pull request #527
Opened 2020-12-01 22:58 UTC by vektor8891

**Changelog:**
 - new pocketlisp function: divisors, range-between, rand-between

2020-12-02 10:28 UTC, maxinteger requested changes
Over all the PR looks good. 
But before merge please fix some minor issues.

FYI I modified the target branch to `feature/move-from-realtimedb-to-firestore`

2020-12-02 10:28 UTC, maxinteger commented on src/shared/script/shared-code.ts
> +		const divisorList = listDivisors(n.value)
Incorrect indentation.
We are using Prettier for correctly format the code.
If you are using VSCode then it can format the code for you when you save the file. Please this description:
https://www.robinwieruch.de/how-to-use-prettier-vscode

you also can fix formatting with the `npm run format` command before commit

2020-12-02 10:28 UTC, maxinteger commented on src/shared/utils/math.ts
> +  var small: number[] = [];
please use `cons` or `let` when you define variable

2020-12-02 10:28 UTC, maxinteger commented on src/shared/utils/math.ts
> +    if (n % i == 0) {
please always use `===` instead of `==` 

the problem is when the operands of  `==` are have different data type JS try to convert them to the same type. `===` always compare values and it is a much more resilient approach.

2020-12-02 10:28 UTC, maxinteger commented on src/shared/utils/math.ts
> +      if (i * i != n)  // Don't include a square root twice
please always use `!==` instead of `!=`

2020-12-02 10:28 UTC, maxinteger commented on README.md
> +A Zsebtanár egy ingyenes és nyíltforráskódú projet. Hálásak vagyunk minden hozzájárulásért - legyen az hibajavítás, dokumentáció frissítése vagy új funkció javaslata. További részletekért olvased el
You can keep these changes, but next time please create a new PR

2020-12-08 04:57 UTC, vektor8891 commented
@maxinteger i did some refactoring on the code. i remember you told me i should use a different way for unit testing. can you provide a reference?

2020-12-08 19:55 UTC, maxinteger approved these changes

2020-12-08 19:57 UTC, merged