Origin/feature/pocketlisp/convert units
zsebtanar/zsebtanar-proto pull request #532
Opened 2020-12-12 03:29 UTC by vektor8891

**Changelog:**
 - feature: convert-units (pocketlisp)

2020-12-12 18:15 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
I think better to use only English words in the script.
Please remove mp, p, ó, óra and hét options

2020-12-12 18:15 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    hüvelyk: 0.0254,
please remove this option

2020-12-12 18:15 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    if (from.value in units) {
sorter if you do this:
```suggestion
    if (from.value in units && to.value in units) {
```

2020-12-12 21:54 UTC, vektor8891 commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
@maxinteger i would like users to be able to use this functions with Hungarian expressions as well. i moved the non-English units into a separate variable. please let me know if this is ok or if you have a better idea, pls let me know.

2020-12-12 22:03 UTC, vektor8891 commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    if (from.value in units) {
@maxinteger I separated the two so that I can distinguish between cases when the 1) units are invalid or 2) they are both valid but don't belong to the same category (e.g. "kg" and "s"). Note that I also raise different errors to these cases. However, if I check them together, I cannot distinguish between 1) and 2). If you have any suggestions, please let me know.

2020-12-13 14:41 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    if (from.value in units) {
Good point

2020-12-13 14:48 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
@vektor8891 I still do not like it :)
this function must do only one thing, convert one unit into another without care about the selected language
I recommend to create another lang utility function which can convert Hungarian unit into English one 
also we should have only one notation for each units, for example only `deg` and no `°`. `°` could be part of the language utils too.

By the way, processing user input is never easy, ex: "óra", "ora", "óRa", "óRA", etc., should be considered as valid unit... So I recommend to be specific in the exercise description so we just need to care about the number.

2020-12-13 14:51 UTC, maxinteger requested changes
I merged your other PR and because you modified the same file in both PR you need to resolve the conflict before we can merge this PR.

The easiest way if you pull the latest version of `feature/move-from-realtimedb-to-firestore` and then and merge it into your branch `feature/pocketlisp/convert_units` branch

2020-12-13 14:51 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +const translations = {
this should be in the language utils

2020-12-15 04:54 UTC, vektor8891 commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
@maxinteger this function is developed for the teachers who will use our platform to create exercises. my aim with adding language specific inputs was that when they create an exercise for e.g. converting time, they would not have to do the translation for themselves but rather can just simply use the units they would use in the introduction e.g.:
```
(def unit-from "óra")
(def unit-to "perc")

Feladat: Hány @unit-to@ az alábbi kifejezés?

(convert-unit 2 unit-from unit-to)
```
i'm happy to separate the translation from the actual conversion. but i would really like to avoid having users to implement their own "dictionaries" e.g.:
```
(def unit-from-hun "óra")
(def unit-to-hun "perc")
(def translations {"óra" "h" "perc" "min"})
(def unit-from (get translations unit-from-hun))
(def unit-to (get translations unit-to-hun))

Feladat: Hány @unit-to-hun@ az alábbi kifejezés?

(convert-unit 2 unit-from unit-to)
```
as for user input, i will provide a list of acceptable units in the [description](https://gist.github.com/vektor8891/7acf7b658720270f553598917cb36359). again, this function will *not* be used by the students but the creators of exercises. so we can expect them to use the units correctly.

2020-12-15 14:03 UTC, maxinteger requested changes

2020-12-15 14:03 UTC, maxinteger commented on src/shared/script/shared-code/langUtils.ts
> +  return str in translations ? translations[str] : str
In general I do not recommend to use `in` operator in JavaScript
`in` check if the key is exists in the object or not but it will return with true even if the value of the key is undefined:
```
"a" in {} // => false
"a" in { a: undefined } // => true 
```
I recommend to do this instead:
```suggestion
  return translations[str] || str
```

2020-12-16 21:09 UTC, maxinteger commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
@vektor8891 I see your point, but I am looking this problem from developer point of view and combining unrelated functionalities never a good idea.
Also this will cause more problem when you add more supported language and this translations happening in different functions.
Much better to centralize the problem under the translation function.
It should work like this: 
```
Feladat: Hány @(translate "hu" "hour")@ az alábbi kifejezés?
```
or you can make it shorter
```
(def hun (translate "hu"))

Feladat: Hány @(hun "hour")@ az alábbi kifejezés?
```

Another possible options is to pass the current language to pocket lisp so it will use the selected language units automatically, but you will need the translate function anyway

2020-12-17 04:27 UTC, vektor8891 commented on src/shared/script/shared-code/unitConvertUtils.ts
> +    ó: 3600,
@maxinteger good point. this makes sense. let me add these features to the list.

2020-12-17 21:30 UTC, merged