Bugfix/pocketlisp/num to text
zsebtanar/zsebtanar-proto pull request #534
Opened 2020-12-12 06:16 UTC by vektor8891

**Issue number:** #517 

**Changelog:**
- fix bug in num-to-text
- add unit tests
- refactoring

2020-12-12 18:31 UTC, maxinteger requested changes

2020-12-12 18:31 UTC, maxinteger commented on src/shared/script/shared-code/utils.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
usually ESLint give us useful notes with warnings
Please do not disable it

2020-12-12 21:29 UTC, vektor8891 commented on src/shared/script/shared-code/utils.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
@maxinteger how can i fix these warnings?
```Unexpected any. Specify a different type.eslint@typescript-eslint/no-explicit-any```
and
```Argument 'a' should be typed with a non-any type.eslint@typescript-eslint/explicit-module-boundary-type```

2020-12-13 14:35 UTC, maxinteger requested changes

2020-12-13 14:35 UTC, maxinteger commented on src/shared/script/shared-code/utils.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
I just checked the file and looks like safe to use `any` in the `assertType` and `typeCheck`

please disable only for these 2 functions the eslint check:
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any 
```

2020-12-15 03:18 UTC, vektor8891 commented on src/shared/script/shared-code/utils.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
fixed

2020-12-15 13:58 UTC, merged