Feature/pocketlisp/suffix
zsebtanar/zsebtanar-proto pull request #536
Opened 2020-12-24 06:17 UTC by vektor8891

**Changelog:**
 - feature: adding functions to handle various Hungarian suffixes (e.g. "szorosára", "edét", "ból")

2020-12-24 06:18 UTC, vektor8891 commented
@maxinteger a small Christmas present from me :)

2020-12-24 06:23 UTC, vektor8891 commented
@maxinteger i temporarily removed fractions from the scope of `num-to-text`. i opened an issue to discuss this separately: #537

2020-12-26 21:57 UTC, vektor8891 commented
@maxinteger i'm done. can you pls have a look? (i might have missed handling some special cases but we can add them later.)

2021-01-16 04:21 UTC, vektor8891 commented
@maxinteger can you pls have a look at this PR?

2021-01-28 20:26 UTC, maxinteger requested changes

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +  // number of trailing zeros after first digit
these comments should be above doc strings, for example:
```
/**
 * Number of trailing zeros after first digit
 */
export function trailingZeros(num: number): number {
```
Note: 
- doc string is must be above the function definition and it starts with `/**` and ends with `*/`, the extra ` *` before each line is optional, but make it more readable
- you do not need to describe the parameters since they are documented via the type definitions

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +export function pitch(n: number): string {
in Typescript you can use so called "string literal" types.
Here the return type is string but more accurately it is just `'high'` and `'low'` strings, what you can define the fallowing way:
```suggestion
export function pitch(n: number): 'low' | 'high' {
```

Not a huge thing but better this way

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +    return highPitch.indexOf(lastDigit) >= 0 ? 'high' : 'low'
better to use `includes` instead of `indexOf` to check if the item is in the array

```suggestion
    return highPitch.includes(lastDigit) ? 'high' : 'low'
```

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +  const lowPitch = pitch(n) === 'low'
Minor thing, but good practices to put `is` prefix before boolean variables `lowPitch` => `isLowPitch`
Helps the readability

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=s)[eoö](?=k)/g, suffixVowel(n, 'oeö')) // -sok/sek/sök
I do not understand why do you need "lookbehind assertions" here
```suggestion
  sfx = sfx.replace(/^(s)[eoö](k)$/g, `$1${suffixVowel(n, 'oeö')}$2`) // -sok/sek/sök
```

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=k)[ae](?=t|l)/g, suffixVowel(n, 'ae')) // -kat/ket/kal/kel
same here
```suggestion
  sfx = sfx.replace(/^(k)[ae](t|l)$/g, `$1${suffixVowel(n, 'ae')}$2`) // -kat/ket/kal/kel
```

2021-01-28 20:26 UTC, maxinteger commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=sz)[oeö](?=r)/g, suffixVowel(n, 'oeö')) // -szor/szer/ször
same as above, not every browser support "lookbehind assertions"

2021-01-29 03:35 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +  // number of trailing zeros after first digit
done.

2021-01-29 03:37 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +    return highPitch.indexOf(lastDigit) >= 0 ? 'high' : 'low'
done.

2021-01-29 03:58 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=s)[eoö](?=k)/g, suffixVowel(n, 'oeö')) // -sok/sek/sök
done.

2021-01-29 03:59 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=sz)[oeö](?=r)/g, suffixVowel(n, 'oeö')) // -szor/szer/ször
done. i've removed all lookahead/lookbehind

2021-01-29 04:05 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +  sfx = sfx.replace(/(?<=k)[ae](?=t|l)/g, suffixVowel(n, 'ae')) // -kat/ket/kal/kel
done.

2021-01-29 04:06 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +  const lowPitch = pitch(n) === 'low'
done

2021-01-29 04:06 UTC, vektor8891 commented on src/shared/script/shared-code/suffixUtils.ts
> +export function pitch(n: number): string {
done.

2021-01-29 04:08 UTC, vektor8891 commented
@maxinteger Thanks for your comments. I've updated the code based on your suggestions.

2021-01-29 17:41 UTC, merged