WIP: add dynamic solution for simpleText
zsebtanar/zsebtanar-proto pull request #548
Opened 2021-02-18 05:17 UTC by vektor8891

**Issue number:** #541 

**Changelog:**
 - handling dynamic text

2021-02-18 05:24 UTC, vektor8891 commented
@maxinteger How can I transform the output of the evalPL function into string array? This works in the console but I'm not if this is the right way to do it: `dynamicSolution.value.map(x => x.value)`. Currently I get the following error: `Type 'string' is not assignable to type 'string[]'.`.

2021-02-21 14:29 UTC, maxinteger requested changes

2021-02-21 14:29 UTC, maxinteger commented on src/client/exercise/components/userControls/dynamicSolution.tsx
> +export function DynamicSolution(ctrl: UCSimpleText): JSX.Element {
Now I see how it looks, and I am not sure anymore extracting this code is a good idea.

You have too many moving parts
- ctrl type different for each field type
- return value of the solution function not always string
- you have to render different user input for each field type (e.g. `SimpleText`, `SingleNumber`, etc.)

Duplicated code not always wrong.

In this case probably better to implement the dynamic solution for each field type and then if we can see a patter then we can extract the necessary code

the SimpleText and the SingleNumber inputs are the easiest ones, they are not good for extrapolate generic solution for all field types

2021-02-23 05:29 UTC, vektor8891 commented on src/client/exercise/components/userControls/dynamicSolution.tsx
> +export function DynamicSolution(ctrl: UCSimpleText): JSX.Element {
@maxinteger I've reverted the changes and implemented the dynamic solution for each input type.

2021-02-23 22:41 UTC, maxinteger requested changes

2021-02-23 22:41 UTC, maxinteger commented on src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> +                  <br />
for multi line code example please use the `<pre>` with `<code>` tag instead
```
<pre>
<code>
(def x 0.12)
(def solution-{data.name} (const x))
</code>
</pre>
```

2021-02-23 22:41 UTC, maxinteger commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +                  <br />
for multi line code example please use the `<pre>` with `<code>` tag instead
```
<pre>
<code>
(def x [&quot;matek&quot; &quot;matematika&quot;])
(def solution-{data.name} (const x))
</code>
</pre>
```

Probably you can create a simple component from this under the `src/client/generic/components`
something like this:
```
interface Props {
  children?: ReactNode
}

export function CodeExample({ children }: Props) {
  return (
    <pre>
      <code>{children}</code>
    </pre>
  )
}
```

then you can use it like:
```
<CodeExample>
(def x [&quot;matek&quot; &quot;matematika&quot;])
(def solution-{data.name} (const x))
</CodeExample>
```

not much saving, but later we can add syntax highlight for example

2021-02-24 05:10 UTC, vektor8891 commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +                  <br />
@maxinteger Thanks for the suggestion. I tried to implement it but the problem is that ESLint automatically merges the two lines and I cannot enforce a linebreak. This is the best idea I have but I feel it's missing the point (being more concise):
```
<CodeExample>(def x [&quot;matek&quot; &quot;matematika&quot;])</CodeExample>
<CodeExample>(def solution-{data.name} (const x))</CodeExample>
```

2021-02-24 20:28 UTC, maxinteger requested changes

2021-02-24 20:28 UTC, maxinteger commented on src/client/generic/components/CodeExample.tsx
> +    <code>
please use `<pre>` tag instead
```
<pre>
    <code>
        {children}
    </code>
</pre>

2021-02-24 20:28 UTC, maxinteger commented on src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> +                      <CodeExample>(def x 0.12)</CodeExample>
you must use a single `<CodeExample>` like:
```
<CodeExample>
   (def x 0.12)
   (def solution-{data.name} (const x))
</CodeExample>

2021-02-24 20:28 UTC, maxinteger commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +                      <CodeExample>(def x [&quot;matek&quot; &quot;matematika&quot;])</CodeExample>
you must use a single `<CodeExample>` like
```
 <CodeExample>
   (def x [&quot;matek&quot; &quot;matematika&quot;])
   (def solution-{data.name} (const x))
</CodeExample
```
if you have problem with line break you can try this:
```
 <CodeExample>{`
   (def x [&quot;matek&quot; &quot;matematika&quot;])
   (def solution-{data.name} (const x))
`}</CodeExample
```

2021-02-24 20:28 UTC, maxinteger commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +      {!!data.isDynamic && <div></div>}
the `!!` ins not necessary since `isDynamic` is a boolean value

2021-02-25 04:11 UTC, vektor8891 commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +                      <CodeExample>(def x [&quot;matek&quot; &quot;matematika&quot;])</CodeExample>
@maxinteger I get your point. However, using `` doesn't enable me to use `data.name` in the middle. Here is what I could come up with:
```
                      <CodeExample>
                        {`(def x ["matek" "matematika"])
(def solution-`}
                        {data.name}
                        {` (const x))`}
                      </CodeExample>
```

2021-02-25 04:11 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +      {!!data.isDynamic && <div></div>}
updated.

2021-02-26 15:16 UTC, maxinteger requested changes

2021-02-26 15:16 UTC, maxinteger commented on src/client/generic/components/form/input/Select.tsx
> +        <option key={idx} value={String(value)}>
The `String` call is unnecessary 
```suggestion
        <option key={idx} value={value}>
```

Also, if you want to convert a value into string the preferred way is to call the `toString` method

2021-02-26 15:16 UTC, maxinteger commented on src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> +                      <CodeExample>
A bit more readable:

```
      <CodeExample>
{`
(def x 0.12)
(def solution-${data.name}
(const x))
`}
      </CodeExample>
```

2021-02-27 04:00 UTC, vektor8891 commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +              </Checkbox>
@maxinteger I'll try to resolve these based on our discussion today.

2021-02-27 04:01 UTC, vektor8891 commented on src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> +                      <CodeExample>
@maxinteger This is what prettier let's me do:
```
                      <CodeExample>
                        {`
(def x 0.12)
(def solution-${data.name} (const x))
`}
                      </CodeExample>
```

2021-02-27 07:00 UTC, vektor8891 commented on src/client/exercise/components/userControls/numberList/NumberListAdmin.tsx
> +    previewCtlr.solution = solution
@maxinteger Can you pls help me how to add `props.fields` to `previewCtrl`? The NumberList component relies on it to display the solution.

2021-02-27 07:01 UTC, vektor8891 commented on src/client/exercise/components/userControls/fractionNumber/FractionNumberAdmin.tsx
> +  let solution: FractionNumber = { numerator: 0, denominator: 0 }
@maxinteger I'm sure there is a better way to implement it...

2021-03-01 23:02 UTC, maxinteger requested changes

2021-03-01 23:02 UTC, maxinteger commented on src/client/exercise/components/userControls/numberList/NumberListAdmin.tsx
> +    previewCtlr.solution = solution
@vektor8891 
`fields` property is similar to the `options` except here you have we use it only for the visual representation and to define how many fields needed.

we can solve it the same way as we did with options:
```
const fields = evalPL(`(fields-${data.name})`) as PLVector<PLHashMap<PLString>>
```

and you can define it like:
```
(def fields-xyz (const [[:prefix "x=" :postfix "m^3"], {}, {} ]
```
this should define 3 fields

2021-03-01 23:02 UTC, maxinteger commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +      solution = dynamicSolution.value.map((x) => x.toString())
```suggestion
      solution = dynamicSolution.toJS()
```

2021-03-02 07:00 UTC, vektor8891 commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +      solution = dynamicSolution.value.map((x) => x.toJS())
@maxinteger the problem is that `toJS()` does not work properly on `PLHashmap` (see issue [here](https://github.com/maxinteger/pocket-lisp-stdlib/issues/17)). do you have any suggestions? should we fix this first?

2021-03-04 05:35 UTC, vektor8891 commented on src/client/exercise/components/userControls/singleNumber/SingleNumberAdmin.tsx
> +                      <CodeExample>
fixed

2021-03-04 05:52 UTC, vektor8891 commented on src/client/exercise/components/userControls/numberList/NumberListAdmin.tsx
> +    previewCtlr.solution = solution
done.

2021-03-04 05:55 UTC, vektor8891 commented on src/client/exercise/components/userControls/fractionNumber/FractionNumberAdmin.tsx
> +  let solution: FractionNumber = { numerator: 0, denominator: 0 }
done.

2021-03-04 05:55 UTC, vektor8891 commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +            {`(def x [{"Rossz választás." false},
done.

2021-03-04 21:46 UTC, maxinteger requested changes

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +  let solution: Map<string, PLString>[] = []
this is wrong because the solution of the binary choice is a boolean list see [here](https://github.com/zsebtanar/zsebtanar-proto/blob/develop/src/shared/exercise/types.ts#L101)

Probably you wanted to define the binary choice `options`, in that case the type is wrong:
```suggestion
  let options: Record<string, string>[] = []
```
The `toJS` method recursively convert every data type from PL to JS
Also I changed `Map` to `Record` because PlainJS object is beheave like a hashMap, but in it is not completely true. In JS you have the Object (`{...}`) and a real HasmMap (`new Map()`).
Unfortunately PL returns with a `Map` but the Binary component looking for Plain Object so after eval you need to convert it.

So it should be like this:
```
  let options: Recrod<string, string>[] = []
  let hasSolution = false
  const hasName = data.name !== undefined
  if (data.isDynamic) {
    const dynamicOptions = evalPL(`(options-${data.name})`) as PLVector<PLHashMap<PLString>>
    if (dynamicOptions !== undefined) {
      options = Object.entries(dynamicOptions.toJS()).reduce((obj, [key, value]) => {
          obj[key] = value
          return obj
      }, {})
      hasSolution = true
    }
  }
```

Beside the options you still need to handle the solutions which should be a boolean array.

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +(def solution-${data.name} (const x))
you defined the options here, not the solution
```suggestion
(def options-${data.name} (const x))
```
Also try to use descriptive variable names in the example instead of `x` you can do this:
```
(def options-map [{"statement" "Ez egy igaz állítás" "solution" true},
```
or
```
(def options-${data.name}-map [{"statement" "Ez egy igaz állítás" "solution" true},
```
you should fix it for all examples

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
do not create manually the component, use the `BinaryChoice` component instead

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/fractionNumber/FractionNumberAdmin.tsx
> +(def solution-${data.name} (const x))
`x` is not needed

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +      solution = dynamicSolution.value.map((x) => x.toJS())
@vektor8891 yes, we should fix PL first
I will do it

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +          <MultiChoice {...previewCtlr}></MultiChoice>
you must import `MultiChoice`

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
you can remove this because `MultiChoice` should render this properly

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/numberList/NumberListAdmin.tsx
> +    const dynamicSolution = evalPL(`(solution-${data.name})`) as PLVector<PLString>
I know the NumerList accept the solution as a string list, but in PL we should use number instead of string
much easier to work with that fro, editor point of view

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/singleChoice/SingleChoiceAdmin.tsx
> +  let solution: Map<string, PLString>[] = []
this is not the solution but the `options` the solution must be a `number`

2021-03-04 21:46 UTC, maxinteger commented on src/client/exercise/components/userControls/singleChoice/SingleChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
please use the `SingleChoice` component instead

2021-03-05 06:00 UTC, vektor8891 commented on src/client/exercise/components/userControls/simpleText/SimpleTextAdmin.tsx
> +      solution = dynamicSolution.value.map((x) => x.toString())
done.

2021-03-05 06:56 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +  let solution: Map<string, PLString>[] = []
@maxinteger I've modified the code a bit. I'm not using PLHashMap anymore. What do you think?

2021-03-05 07:00 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +(def solution-${data.name} (const x))
@maxinteger I've created separate variables for statements, options, labels, and random-order.

2021-03-05 07:02 UTC, vektor8891 commented on src/client/exercise/components/userControls/fractionNumber/FractionNumberAdmin.tsx
> +(def solution-${data.name} (const x))
@maxinteger I'd still like to keep it because usually `x` is generated, not constant. I've updated the variable name.

2021-03-06 04:39 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +  let solution: Map<string, PLString>[] = []
@maxinteger I've updated the code to follow the structure of the React object. Please have a look. I've noticed one thing though: for some reason now you cannot use `:keyword` in PLHashMap because the semicolon will remain in the string after the function is evaluated. Is this a bug?

2021-03-07 05:57 UTC, vektor8891 commented on src/client/exercise/components/userControls/singleChoice/SingleChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
done

2021-03-07 06:03 UTC, vektor8891 commented on src/client/exercise/components/userControls/numberList/NumberListAdmin.tsx
> +    const dynamicSolution = evalPL(`(solution-${data.name})`) as PLVector<PLString>
done.

2021-03-07 06:03 UTC, vektor8891 commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
done.

2021-03-07 06:03 UTC, vektor8891 commented on src/client/exercise/components/userControls/multiChoice/MultiChoiceAdmin.tsx
> +          <MultiChoice {...previewCtlr}></MultiChoice>
done.

2021-03-07 06:03 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +          {solution.map((item, idx) => (
done.

2021-03-07 06:06 UTC, vektor8891 commented on src/client/exercise/components/userControls/binaryChoice/BinaryChoiceAdmin.tsx
> +  let solution: Map<string, PLString>[] = []
@maxinteger I've updated the code. I will create a new issue for the last comment, let's discuss it separately.

2021-03-07 06:21 UTC, merged

2021-03-07 06:24 UTC, vektor8891 commented
@maxinteger Apologies. I accidentally merged the changes into develop. I didn't intend to. I tried to revert it but unfortunately couldn't.