fix typo
zsebtanar/zsebtanar-proto pull request #584
Opened 2021-04-08 03:57 UTC by vektor8891

fix typo

2021-04-08 22:46 UTC, maxinteger requested changes

2021-04-08 22:46 UTC, maxinteger commented on src/shared/math/random.spec.ts
> +        console.log(res)
please remove the `console.log`

2021-04-08 22:46 UTC, maxinteger commented on src/shared/math/random.spec.ts
> +      function checkDistribution(range: number) {
next time please create a separated PR for changes which are not related to the original problem
In this case distribution check is not related to the typo

2021-04-09 03:45 UTC, vektor8891 commented on src/shared/math/random.spec.ts
> +        console.log(res)
done.

2021-04-09 03:46 UTC, vektor8891 commented on src/shared/math/random.spec.ts
> +      function checkDistribution(range: number) {
@maxinteger Apologies for the mess, these changes were not intentional. I removed them now. Can you pls have a look?

2021-04-09 03:46 UTC, vektor8891 commented
@maxinteger Apologies for the mess, these changes were not intentional. I removed them now. Can you pls have a look?

2021-04-09 09:53 UTC, maxinteger approved these changes

2021-04-09 09:54 UTC, merged