feature: add gcd function
zsebtanar/zsebtanar-proto pull request #615
Opened 2021-06-12 05:14 UTC by vektor8891

**Issue number:** #614 

**Changelog:**
 - add gcd function

2021-06-13 22:30 UTC, maxinteger requested changes

2021-06-13 22:30 UTC, maxinteger commented on src/shared/script/shared-code/utils.ts
> +export const plFnNumNum2Num = (fn: (x: number, y: number) => number) => (
Pleas change the function name, it describe only the input and output values and not the purpose of the function.
If I just read the function name, I have no clue what it does.

Probably we need another naming convention to help code readers
for example: `fnWrapperNum2String` or `fnWrapperNumToStr` so `fnWrapper2NumToNum` sound better.

2021-06-15 13:22 UTC, vektor8891 commented on src/shared/script/shared-code/utils.ts
> +export const plFnNumNum2Num = (fn: (x: number, y: number) => number) => (
@maxinteger Done.

2021-06-17 21:35 UTC, maxinteger approved these changes

2021-06-17 21:37 UTC, merged